urls:
  google : "https://www.google.com/search?q="
  baidu : "https://www.baidu.com/s?wd="
  duckduckgo : "https://duckduckgo.com/html/?q="
  bing : "https://www.bing.com/search?q="

apps:
  safari : "open -a /Applications/Safari.app %s"
  chrome : "open -a '/Applications/Google Chrome.app' %s"
  firefox : "open -a /Applications/Firefox.app %s"